name: hola-mundo #Nombre del workflow
on: [push] #evento que lo activará
jobs: #Definición de los jobs
  hola-mundo: #Nombre del job
    runs-on: ubuntu-latest #Maquina en la que correrá
    steps: #Lista de steps del job hola-mundo
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: 18
      - name: Run index
        run: node index.js
